# Workflow: Rust CI
# Description: This workflow runs builds and tests the project on every push.
# Date: August 2024

name: Unity CI

on:
  push:
    branches: [ "main", "lab" ]
  pull_request:
    branches: [ "main", "lab" ]

env:
  RUST_CI_VERSION: 2024.8.3.0a0-lab
  RUST_CI_AUTHOR: sascharo

jobs:
  test:
    name: Test 🧪
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@main
        with:
          lfs: true

      # Cache
      - uses: actions/cache@main
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-

      # Test
      
  build:
    name: Build my project ✨
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@main
        with:
          lfs: true

      # Cache
      - uses: actions/cache@main
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-

       # Build
      